### 索引切片

In [1]:
import numpy as np

nd2 = np.random.randint(-5,15,size = (5,6))

nd2

array([[14,  3, 14,  4, 10,  3],
       [ 3, -3,  8,  5, 10,  2],
       [ 4, -5, 11,  7,  8, 12],
       [ 7, 14, 14,  9, -4, -1],
       [13,  8, 12,  9, -5,  6]])

In [2]:
nd2[[1,3]]

array([[ 3, -3,  8,  5, 10,  2],
       [ 7, 14, 14,  9, -4, -1]])

In [3]:
nd2[:,[1,3,5]]

array([[ 3,  4,  3],
       [-3,  5,  2],
       [-5,  7, 12],
       [14,  9, -1],
       [ 8,  9,  6]])

In [4]:
nd2[[1,3],[1,3,5]] # 成对出现，（1,1）（3,3），后面5无法结合

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [5]:
nd2[[1,3],[3,5]]

array([ 5, -1])

#### 方式一：

In [6]:
nd2[[1,3]][:,[1,3,5]]

array([[-3,  5,  2],
       [14,  9, -1]])

#### 方式二

In [8]:
index = np.ix_([1,3],[1,3,5])

nd2[index] # 相当于 nd2[[1,3]][:,[1,3,5]]

array([[-3,  5,  2],
       [14,  9, -1]])

### 形状改变

#### reshape

In [18]:
nd2 = np.random.randint(0,100,size = (3,4))

display(nd2) # 美观
# print(nd2)

# 数据重塑reshape
display(nd2.reshape(4,3)) # 一行行数，接龙~

print('2行6列：')
display(nd2.reshape(2,6))
# -1表示，最后算，相当于 x * 6 = 3 * 4----> x = 2
display(nd2.reshape(-1,6)) # 适合，不关心总数，灵活，预先算

display(nd2.reshape(-1)) # 自动算

array([[97, 42, 49, 92],
       [88, 31, 54, 33],
       [19, 74, 62, 13]])

array([[97, 42, 49],
       [92, 88, 31],
       [54, 33, 19],
       [74, 62, 13]])

2行6列：


array([[97, 42, 49, 92, 88, 31],
       [54, 33, 19, 74, 62, 13]])

array([[97, 42, 49, 92, 88, 31],
       [54, 33, 19, 74, 62, 13]])

array([97, 42, 49, 92, 88, 31, 54, 33, 19, 74, 62, 13])

In [19]:
nd2.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

#### 叠加

In [22]:
arr1 = np.random.randint(0,10,size = (2,4))

arr2 = np.random.randint(-5,5,size = (3,4))

display(arr1,arr2)

# 合并，默认进行行合并，行变多
np.concatenate([arr1,arr2,arr1])

array([[6, 3, 4, 2],
       [2, 2, 4, 4]])

array([[-4,  4,  1,  4],
       [-1,  0, -3, -1],
       [ 4,  1,  3, -3]])

array([[ 6,  3,  4,  2],
       [ 2,  2,  4,  4],
       [-4,  4,  1,  4],
       [-1,  0, -3, -1],
       [ 4,  1,  3, -3],
       [ 6,  3,  4,  2],
       [ 2,  2,  4,  4]])

In [27]:
arr1 = np.random.randint(0,10,size = (3,5))

arr2 = np.random.randint(-5,5,size = (3,4))

display(arr1,arr2)

# 是否可以合并？
# axis = 0默认值，代表行
# axis = 1表示列，-1表示倒着数
np.concatenate([arr1,arr2],axis = -1)

array([[8, 1, 4, 0, 9],
       [6, 9, 7, 8, 4],
       [8, 0, 7, 3, 6]])

array([[ 4, -5, -2,  3],
       [ 3,  0, -3,  3],
       [ 2, -5,  1,  0]])

array([[ 8,  1,  4,  0,  9,  4, -5, -2,  3],
       [ 6,  9,  7,  8,  4,  3,  0, -3,  3],
       [ 8,  0,  7,  3,  6,  2, -5,  1,  0]])

#### 拆分

In [33]:
nd = np.random.randint(0,100,size = (6,9))

display(nd)

# 行拆分，一个数字，表示平均分成多少份
# 列表，表示，节点进行拆分
np.split(nd,[1,4,5],axis = 0)

print('下面是列拆分：')
np.split(nd,[1,4,5],axis = 1)

array([[36, 34, 93, 96, 80, 96, 46, 29, 38],
       [31, 63, 61, 64, 13, 97, 40, 80, 40],
       [41, 67,  6, 50, 85, 65, 95, 43, 64],
       [19, 30, 42, 83, 73, 24, 22, 73,  8],
       [76, 52, 16, 54, 72, 38, 64, 17, 49],
       [18, 58, 69, 89, 25,  9, 18, 19, 65]])

下面是列拆分：


[array([[36],
        [31],
        [41],
        [19],
        [76],
        [18]]),
 array([[34, 93, 96],
        [63, 61, 64],
        [67,  6, 50],
        [30, 42, 83],
        [52, 16, 54],
        [58, 69, 89]]),
 array([[80],
        [13],
        [85],
        [73],
        [72],
        [25]]),
 array([[96, 46, 29, 38],
        [97, 40, 80, 40],
        [65, 95, 43, 64],
        [24, 22, 73,  8],
        [38, 64, 17, 49],
        [ 9, 18, 19, 65]])]

#### 数组转置

In [35]:
A = np.random.randint(0,10,size = (3,5))

print('原数据：')
display(A)

print('reshape:')
display(A.reshape(5,3))

print('转置，行变列，列变成行：')
display(A.T)

原数据：


array([[2, 4, 5, 1, 6],
       [2, 5, 5, 3, 7],
       [0, 3, 8, 7, 3]])

reshape:


array([[2, 4, 5],
       [1, 6, 2],
       [5, 5, 3],
       [7, 0, 3],
       [8, 7, 3]])

转置，行变列，列变成行：


array([[2, 2, 0],
       [4, 5, 3],
       [5, 5, 8],
       [1, 3, 7],
       [6, 7, 3]])

In [36]:
np.transpose(A,axes = [1,0])

array([[2, 2, 0],
       [4, 5, 3],
       [5, 5, 8],
       [1, 3, 7],
       [6, 7, 3]])

### 广播

In [38]:
arr1 = np.random.randint(0,10,size = (5,3))

arr2 = np.arange(1,4)
display(arr1,arr2)

# arr2 只有一行，arr1 5行
# 广播机制，arr2 变身，变成了5份，每一份和每一行相加~
arr1 + arr2

array([[8, 9, 2],
       [5, 9, 2],
       [7, 0, 0],
       [0, 7, 3],
       [8, 1, 0]])

array([1, 2, 3])

array([[ 9, 11,  5],
       [ 6, 11,  5],
       [ 8,  2,  3],
       [ 1,  9,  6],
       [ 9,  3,  3]])

In [41]:
# 一行中，有5个数
arr3 = np.random.randint(0,10,size = (4,5))

# 每一行的平均值，4个数 == 4行
arr4 = arr3.mean(axis = 1)

display(arr3,arr4)

# 每一行，减去每一行的平均值
# arr3 - arr4 # 形状不匹配，所以报错

# 形状改变，4行一列
display(arr4.reshape(4,1))

# arr3有4列，arr4改变形状，变成了4列
# 广播
arr3 - arr4.reshape(4,1)

array([[7, 3, 7, 3, 2],
       [5, 0, 6, 4, 8],
       [5, 4, 2, 5, 3],
       [3, 2, 8, 9, 7]])

array([4.4, 4.6, 3.8, 5.8])

array([[4.4],
       [4.6],
       [3.8],
       [5.8]])

array([[ 2.6, -1.4,  2.6, -1.4, -2.4],
       [ 0.4, -4.6,  1.4, -0.6,  3.4],
       [ 1.2,  0.2, -1.8,  1.2, -0.8],
       [-2.8, -3.8,  2.2,  3.2,  1.2]])

In [43]:
import numpy as np
arr1 = np.array([0,1,2,3,4,5,6,7]*3).reshape(3,4,2) #shape(3,4,2)
arr2 = np.array([0,1,2,3,4,5,6,7]).reshape(4,2) #shape(4,2)

print('三维数组：')
display(arr1)

print('二维数组：')
display(arr2)

arr3 = arr1 + arr2 # arr2数组在0维上复制3份 shape(3,4,2)
arr3

三维数组：


array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

二维数组：


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]]])

### 通俗函数

#### 一般函数

In [46]:
np.sin(np.pi/2)

1.0

In [50]:
np.cos(np.pi/2).round(1) # 保留几位小数

6.123233995736766e-17

In [52]:
np.sqrt(1024) # 开平方

32.0

In [54]:
# 平方
np.square(8)

64

In [55]:
def fun(x):
    return x**3

fun(3)

27

In [69]:
def fun2(x):
    return x**(1/3)

fun2(27) # 27 = 3 * 3 * 3  

3.0

In [63]:
np.power(9,3)

729

In [72]:
np.power(64,1/3)

3.9999999999999996

In [64]:
np.log2(16)

4.0

In [65]:
x = np.array([1,5,2,9,3,6,8])
y = np.array([2,4,3,7,1,9,0])
np.maximum(x,y) # 返回两个数组中的比较大的值

array([2, 5, 3, 9, 3, 9, 8])

In [68]:
arr2 = np.random.randint(0,10,size = (2,2))
display(arr2)
display(arr2[0])
np.inner(arr2[0],arr2) #返回一维数组向量内积

array([[8, 3],
       [9, 4]])

array([8, 3])

array([73, 84])

In [73]:
a = 3.9999
np.ceil(a)

4.0

In [74]:
np.floor(a)

3.0

In [75]:
arr = np.random.randint(0,30,size = (20))

arr

array([ 5,  8, 19, 16,  3, 10, 27, 21, 18, 16,  2, 20, 27,  8,  8, 19, 11,
       19,  4,  3])

In [76]:
# clip裁剪，10：小于10，拔高，变成10
# 20：大于20不行，消掉，变成20
np.clip(arr,10,20)

array([10, 10, 19, 16, 10, 10, 20, 20, 18, 16, 10, 20, 20, 10, 10, 19, 11,
       19, 10, 10])

#### where

In [77]:
import numpy as np
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])

cond = np.array([True,False,True,True,False])

# 根据条件进行筛选
np.where(cond,arr1,arr2) # True选择arr1，False选择arr2的值

array([ 1,  4,  5,  7, 10])

In [78]:
np.maximum(arr1,arr2) # 每一列最大值

array([ 2,  4,  6,  8, 10])

In [80]:
arr3 = np.random.randint(0,30,size = 20)

display(arr3)

np.where(arr3 < 15,arr3,1024) # 小于15还是自身的值，大于15设置成-15

array([28, 13,  5, 26, 29, 24, 20, 16,  3, 28, 27, 16, 24, 12, 28, 12, 22,
       19, 12,  9])

array([1024,   13,    5, 1024, 1024, 1024, 1024, 1024,    3, 1024, 1024,
       1024, 1024,   12, 1024,   12, 1024, 1024,   12,    9])

In [81]:
# 高考数学，成绩，小0分大于15分，错误，成绩调整一个数字：-1024
arr4 = np.random.randint(-10,180,size = 50)
arr4

array([ 25, 149, 168,  85, 164,  43,  -1,  50,  67, 125,   4,  98, 154,
       145,  -6,  68,  42,  38,  54, 103,  28,  57,  13, 153, 167,  45,
       171, 178,  62, 144,  95, 176, 131, 169,  88,  68,  99,   8, 141,
       146, 128,  22, 177,  73,  30,  92,  -3,  12,  38,  23])

In [87]:
np.where((arr4 < 0) | (arr4 > 150),1024, arr4)

array([  25,  149, 1024,   85, 1024,   43, 1024,   50,   67,  125,    4,
         98, 1024,  145, 1024,   68,   42,   38,   54,  103,   28,   57,
         13, 1024, 1024,   45, 1024, 1024,   62,  144,   95, 1024,  131,
       1024,   88,   68,   99,    8,  141,  146,  128,   22, 1024,   73,
         30,   92, 1024,   12,   38,   23])

#### 集合运算函数

In [88]:
A = np.array([2,4,6,8])
B = np.array([3,4,5,6])

print('交集：')
print(np.intersect1d(A,B)) # 交集 array([4, 6])

# 两者合并，去重
print('并集：\n',np.union1d(A,B)) # 并集 array([2, 3, 4, 5, 6, 8])

# A中有，B中没有
print('差集：\n',np.setdiff1d(A,B)) #差集，A中有，B中没有 array([2, 8])

交集：
[4 6]
并集：
 [2 3 4 5 6 8]
差集：
 [2 8]


### 矩阵运算

In [89]:
#矩阵的乘积
A = np.array([[4,2,3],
              [1,3,1]]) # shape(2,3)
B = np.array([[2,7],
              [-5,-7],
              [9,3]]) # shape(3,2)

print('点乘，矩阵运算:\n', np.dot(A,B)) # 矩阵运算 A的最后一维和B的第一维必须一致


A @ B # 符号 @ 表示矩阵乘积运算

点乘，矩阵运算:
 [[ 25  23]
 [ -4 -11]]


array([[ 25,  23],
       [ -4, -11]])

In [90]:
A.dot(B)

array([[ 25,  23],
       [ -4, -11]])

In [94]:
#计算矩阵的逆
np.set_printoptions(suppress=True)
from numpy.linalg import inv,det,eig,qr,svd
A = np.array([[1,2,3],
              [2,3,4],
              [4,5,8]]) # shape(3,3)
B = inv(A) # 逆矩阵

A.dot(B)

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [95]:
a = 5

b = 0.2

a * b

1.0

In [96]:
det(A)#计算矩阵行列式

-2.0000000000000004

In [97]:
A = np.random.randint(0,10,size = (3,2))

A

array([[5, 8],
       [8, 2],
       [8, 1]])

In [102]:
B = A.reshape(2,3)

C  = np.concatenate([B,np.full(shape = (3,3),fill_value=0)])

D = np.concatenate([C,np.zeros(shape = (5,2))],axis = 1)
D

array([[5., 8., 8., 0., 0.],
       [2., 8., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])