# 作业

In [1]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [4]:
arr1 = np.zeros(shape=10)
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2、创建一个元素为从10到49的ndarray对象，间隔是1

In [15]:
arr2 = np.linspace(10, 49, num=(50-10))
arr2

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

3、将第2题的所有元素位置反转

In [20]:
arr2[::-1]

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [22]:
arr3 = np.random.random(size=(10, 10))
arr3, np.max(arr3)

(array([[0.47986286, 0.11982582, 0.38226862, 0.72344015, 0.25049275,
         0.48164417, 0.80157932, 0.68083973, 0.94146815, 0.08388903],
        [0.76853864, 0.80931819, 0.61818215, 0.50502986, 0.85455785,
         0.15917552, 0.17680551, 0.86735644, 0.14389881, 0.05059048],
        [0.14241565, 0.21233994, 0.74794509, 0.37737657, 0.37251267,
         0.96150077, 0.44265281, 0.87705291, 0.54121982, 0.14349244],
        [0.44490643, 0.05160026, 0.39096667, 0.39463119, 0.51560388,
         0.31355553, 0.15537592, 0.2153453 , 0.30166689, 0.38720104],
        [0.71618414, 0.70504338, 0.6670299 , 0.4926408 , 0.1011598 ,
         0.14619477, 0.89465321, 0.65171456, 0.59651709, 0.43581699],
        [0.45073446, 0.0570134 , 0.22234296, 0.35593531, 0.03395051,
         0.62259032, 0.93178432, 0.72720602, 0.25317159, 0.28706918],
        [0.47050693, 0.22200275, 0.32595242, 0.68172035, 0.23371966,
         0.90184056, 0.85749308, 0.63248627, 0.38016966, 0.02858549],
        [0.71899205, 0.1060

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0


6、创建一个每一行都是从0到4的5*5矩阵

7、创建一个范围在(0,1)之间的长度为12的等差数列，创建[1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024]等比数列。

8、创建一个长度为10的正太分布数组np.random.randn并排序

9、创建一个长度为10的随机数组并将最大值替换为-100

10、如何根据第3列大小顺序来对一个5*5矩阵排序？