### 作业1
给定一个4维矩阵，如何得到最后两维的和？（提示，指定axis进行计算）

In [7]:
import numpy as np

arr = np.random.randint(0,10,size = (2,3,4,5))

display(arr.shape)
# 最后两维的和，指定轴即可
print('求和：')
arr.sum(axis = (-1,-2)).shape

(2, 3, 4, 5)

求和：


(2, 3)

###  作业2  
给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [8]:
import numpy as np

arr1 = np.arange(1,6)
print(arr1)

arr2 = np.zeros(shape = 17,dtype = np.int16)
print(arr2)

# 有间隔的，取出数据并进行替换
# 特定位置的数据进行赋值操作
arr2[::4] = arr1
print('替换之后的数据为：\n',arr2)

[1 2 3 4 5]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
替换之后的数据为：
 [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


### 作业3  
给定一个二维矩阵（5行4列），如何交换其中两行的元素（提示：任意调整，花式索引）？

In [9]:
import numpy as np

arr = np.random.randint(0,100,size = (5,4))

print('调整前：\n', arr)

arr = arr[[0,2,1,3,4]]
print('调整后：\n', arr)

调整前：
 [[31  1 26 69]
 [25 87 92 93]
 [80 58 69 43]
 [42 81 55 52]
 [73 31 88 55]]
调整后：
 [[31  1 26 69]
 [80 58 69 43]
 [25 87 92 93]
 [42 81 55 52]
 [73 31 88 55]]


### 作业4  
创建一个100000长度的随机数组，使用两种方法对其求三次方（1、for循环；2、NumPy自带方法），并比较所用时间(指令：%%time，可以计算运行时间)

In [10]:
%%time
import numpy as np
arr = np.random.randint(0,10,size = 100000)
print('原数据',arr[:10])
arr3 = np.power(arr,3)
print('NumPy默认方法求三次幂：',arr3[:10])

原数据 [6 3 7 3 5 0 2 5 9 2]
NumPy默认方法求三次幂： [216  27 343  27 125   0   8 125 729   8]
Wall time: 2 ms


In [11]:
%%time
import numpy as np
arr = np.random.randint(0,10,size = 100000)
print('原数据：', arr[:10])
result = []
for i in arr:
    result.append(i**3)
print('for循环求三次幂结果：', result[:10])

原数据： [3 0 7 1 8 3 2 8 1 1]
for循环求三次幂结果： [27, 0, 343, 1, 512, 27, 8, 512, 1, 1]
Wall time: 26.9 ms


### 作业5   
创建一个5行3列随机矩阵和一个3行2列随机矩阵，求矩阵积

In [12]:
import numpy as np

A = np.random.randint(0,10,size = (5,3))
B = np.random.randint(0,10,size = (3,2))
display(A,B)

print('方式一：\n',np.dot(A,B)) # 调用NumPy函数dot
print('方式二：\n',A.dot(B)) # 调用对象方法
print('方式三：\n',A @ B) # 使用符号计算

array([[3, 8, 5],
       [6, 6, 3],
       [4, 4, 8],
       [3, 1, 7],
       [9, 4, 1]])

array([[1, 7],
       [3, 6],
       [1, 7]])

方式一：
 [[ 32 104]
 [ 27  99]
 [ 24 108]
 [ 13  76]
 [ 22  94]]
方式二：
 [[ 32 104]
 [ 27  99]
 [ 24 108]
 [ 13  76]
 [ 22  94]]
方式三：
 [[ 32 104]
 [ 27  99]
 [ 24 108]
 [ 13  76]
 [ 22  94]]


### 作业6  
矩阵的每一行的元素都减去该行的平均值（注意，平均值计算时指定axis，以及减法操作时形状改变）

In [17]:
import numpy as np

X = np.random.randint(0,10,size = (3,5))
display(X)

print('计算每一行平均值：')
display(X.mean(axis = 1))

print('每一行的元素都减去该行的平均值：')
# 注意，求了平均值，形状改变（变成二维，便于广播）
X - X.mean(axis = 1).reshape(-1,1)

array([[6, 5, 5, 6, 4],
       [5, 1, 1, 4, 0],
       [8, 0, 3, 1, 4]])

计算每一行平均值：


array([5.2, 2.2, 3.2])

每一行的元素都减去该行的平均值：


array([[ 0.8, -0.2, -0.2,  0.8, -1.2],
       [ 2.8, -1.2, -1.2,  1.8, -2.2],
       [ 4.8, -3.2, -0.2, -2.2,  0.8]])

### 作业7  
打印出以下函数（要求使用np.zeros创建8*8的矩阵）：

In [18]:
import numpy as np

arr = np.zeros(shape = (8,8),dtype=np.int16)

print('原数据：')
display(arr)
# 将奇数行，欧数列，进行修改
arr[::2,1::2] = 1

# 将偶数行，奇数行，进行修改
arr[1::2,::2] = 1

print('修改后的数据是：')
arr

原数据：


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

修改后的数据是：


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int16)

### 作业8  
正则化一个5行5列的随机矩阵（数据统一变成0~1之间的数字，相当于进行缩小）
正则的概念：矩阵A中的每一列减去这一列最小值，除以每一列的最大值减去每一列的最小值（提示：轴axis给合适的参数！！！）

<font size = 6 >$\rm{ A = \frac{A - A.min}{A.max - A.min}}$</font>

In [19]:
import numpy as np

A = np.random.randint(1,10,size = (5,5))
print('原数据为：')
display(A)

# 根据公式进行计算，注意axis，要正确指定
B = (A - A.min(axis = 0))/(A.max(axis = 0) - A.min(axis = 0))
print('正则化后：')
B

原数据为：


array([[7, 6, 5, 4, 5],
       [6, 1, 8, 2, 6],
       [5, 4, 4, 5, 5],
       [3, 3, 4, 5, 8],
       [6, 6, 7, 2, 9]])

正则化后：


array([[1.        , 1.        , 0.25      , 0.66666667, 0.        ],
       [0.75      , 0.        , 1.        , 0.        , 0.25      ],
       [0.5       , 0.6       , 0.        , 1.        , 0.        ],
       [0.        , 0.4       , 0.        , 1.        , 0.75      ],
       [0.75      , 1.        , 0.75      , 0.        , 1.        ]])

In [22]:
A.min(axis = 1) # axis = 1一行的最小值
A.min(axis = 0) # axis = 0 一列的最小值

array([3, 1, 4, 2, 5])

### 作业9  

如何根据两个或多个条件过滤numpy数组。加载鸢尾花数据，根据第一列小于5.0并且第三列大于1.5作为条件，进行数据筛选。（提示，需要使用逻辑与运算：&）

In [25]:
import numpy as np

# 加载了文本文件，储存数据都是结构化的数据
# 花萼长度、花萼宽度、花瓣长度、花瓣宽度
iris = np.loadtxt('./iris.csv',delimiter = ',')

iris.shape

cond1 = iris[:,0] < 5 # 第一列小于5.0
cond2 = iris[:,2] > 1.5 # 第三列大于1.5

cond = cond1 & cond2 # 合并条件

# 获取数据
iris[cond]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### 作业10  

计算鸢尾花数据**每一行**的softmax得分（exp表示自然底数e的幂运算）

In [26]:
np.exp(2) # 幂运算，底数是自然底数e = 2.718

7.38905609893065

In [29]:
np.e**2 # 相当于np.exp

7.3890560989306495

In [30]:
arr = np.array([2,1,0.1])
arr

array([2. , 1. , 0.1])

In [33]:
exp = np.exp(arr)

(exp/exp.sum()).round(1)

array([0.7, 0.2, 0.1])

In [34]:
import numpy as np

iris = np.loadtxt('./iris.csv',delimiter = ',')

print('未计算之前：\n', iris[:5])

def softmax(x):
    exp = np.exp(x)
    # 每一行求和，并且进行形状改变（变成二维，可以进行广播）
    # axis = 1 表示计算每一行的和
    # reshape，广播
    result = exp/exp.sum(axis = 1).reshape(-1,1)
    return result.round(3) # 保留3位小数

result = softmax(iris)
print('softmax得分：\n',result[:5])

未计算之前：
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
softmax得分：
 [[0.81  0.164 0.02  0.006]
 [0.841 0.126 0.025 0.008]
 [0.789 0.176 0.026 0.009]
 [0.781 0.174 0.035 0.01 ]
 [0.78  0.192 0.021 0.006]]


In [36]:
result.sum(axis = 1)

array([1.   , 1.   , 1.   , 1.   , 0.999, 1.   , 1.   , 1.   , 1.   ,
       1.001, 1.001, 1.   , 1.001, 1.   , 1.   , 1.001, 0.999, 1.   ,
       1.001, 0.999, 1.   , 0.999, 0.999, 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 0.999, 0.999, 1.001, 1.001, 1.   ,
       1.   , 1.   , 0.999, 0.999, 1.001, 1.   , 1.   , 1.   , 1.   ,
       1.001, 1.   , 0.999, 1.   , 1.   , 1.   , 1.   , 0.999, 1.   ,
       1.001, 1.   , 0.999, 1.001, 0.999, 1.   , 1.   , 1.   , 1.   ,
       0.999, 0.999, 1.   , 1.   , 1.   , 1.   , 0.999, 1.   , 1.   ,
       1.   , 1.001, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 0.999,
       1.   , 0.999, 0.999, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.001, 1.   , 1.   , 1.   , 0.999, 1.   , 0.999, 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 0.999, 1.   , 1.   , 1.   , 1.   , 0.999, 0.999,
       1.   , 1.   , 1.001, 1.001, 0.999, 0.999, 1.   , 1.001, 0.999,
       1.001, 0.999,