### 作业1

In [1]:
import numpy as np

arr = np.zeros(10,dtype = 'int')

# 注意第5个元素对应索引是4
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 作业2

In [5]:
import numpy as np

# 注意，包含49，所以范围给的是10 ~ 50，可以取到10，但是取不到50
arr = np.arange(10,50)
arr2 = np.linspace(10,49,40,dtype=np.int16)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49], dtype=int16)

### 作业4

In [7]:
import numpy as np

# 生成0~1之间的随机小数
arr = np.random.randint(0,100,size = 30)
display(arr)

# 考察函数使用
print('输出最大值：',arr.max())
print('输出最小值：',arr.min())

array([50, 21,  9, 17, 98, 44, 63, 28, 55,  4, 21, 17, 85,  1, 11, 55, 23,
       44, 43, 67, 91, 53, 86, 43, 93, 68, 36, 32, 66,  6])

输出最大值： 98
输出最小值： 1


### 作业5

In [10]:
arr = np.zeros(shape = (10,10),dtype = np.int8)

arr[[0,-1]] = 1 # 索引、行变换，赋值
arr[:,[0,-1]] = 1

arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

### 作业6

In [13]:
arr = np.full(shape = (5,5),fill_value=3.14)


arr2 = np.arange(0,5)

arr[:] = arr2

arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 作业7

In [17]:
np.set_printoptions(suppress=True)
np.logspace(-3,10,base = 4,num = 11) # 等比数列

array([      0.015625  ,       0.09473229,       0.57434918,
             3.48220225,      21.11212657,     128.        ,
           776.04688205,    4705.06846207,   28526.20085809,
        172950.54088083, 1048576.        ])

### 作业8

In [18]:
import numpy as np

# 创建随机数组
arr = np.random.randn(10)
print('未排序：',arr)

# 注意调用np.sort()方法，要接收一下数据
# 原来的arr并没有改变
arr2 = np.sort(arr)
print('排序后：',arr2)

未排序： [ 0.21544033  1.41067909  0.84189422  0.79528112 -0.59399019  1.22682181
 -1.05607281 -0.89432473 -1.35657179 -0.11982268]
排序后： [-1.35657179 -1.05607281 -0.89432473 -0.59399019 -0.11982268  0.21544033
  0.79528112  0.84189422  1.22682181  1.41067909]


### 作业9

In [20]:
import numpy as np

# 设置不显示科学计数法，默认情况显示情况是：3.22449e-01
np.set_printoptions(suppress = True)

arr = np.random.random(10)
print('原数据：\n',arr)

# 找到最大值
v = arr.max()

# 花式索引
# 进行条件判断
cond = arr == v
print('最大值条件：\n',cond)

# 根据条件，赋值
arr[cond] = -100
print('修改之后数据：\n',arr)

原数据：
 [0.52645349 0.9895991  0.44058396 0.15420042 0.33725979 0.56146253
 0.10336838 0.16735032 0.79705103 0.75954352]
最大值条件：
 [False  True False False False False False False False False]
修改之后数据：
 [   0.52645349 -100.            0.44058396    0.15420042    0.33725979
    0.56146253    0.10336838    0.16735032    0.79705103    0.75954352]


### 作业10

In [21]:
arr = np.random.randint(0,100,size = 5)

arr

array([ 9, 33, 44, 18, 68])

In [23]:
np.sort(arr)[::-1]

array([68, 44, 33, 18,  9])

In [25]:
index = np.argsort(arr) # 索引

print(index)

# 根据索引进行排序
# 花式索引
arr[index]

[0 3 1 2 4]


array([ 9, 18, 33, 44, 68])

In [26]:
nd = np.random.randint(0,30,size = (5,5))
nd

array([[ 6, 24,  8, 24, 26],
       [ 4,  7,  9, 11,  7],
       [ 5, 19,  6, 26, 18],
       [13,  8, 24,  3, 22],
       [27, 22,  5,  9, 11]])

In [29]:
# 获取第三列，并且获取第三列索引的顺序
index = nd[:,2].argsort()

# 根据第三列的索引顺序，对nd进行排序
# 花式索引
nd[index]

array([[27, 22,  5,  9, 11],
       [ 5, 19,  6, 26, 18],
       [ 6, 24,  8, 24, 26],
       [ 4,  7,  9, 11,  7],
       [13,  8, 24,  3, 22]])